### ISSUE TITLE
Does it works properly with Xcode 9? 

### ISSUE THREAD

**Issue by peseriusz** [HelmMobile/clean-swift-templates#3]
Can someone check and confirm? I'm getting for example autogenerated file like "MainListViewControllerViewController" which doesn't works properly.

**Comment by Mijail** [comment]
No, it's not updated. We are working on a new updated version, stay tuned :)

**Comment by Mijail** [comment]
The last pull requested solved this. Anyway we will make a new repo with the new templates and a lot of new features, featuring our way of working with DI.
